# -*- coding: utf-8 -*-
"""QUÉ BUSCA MEDIR CADA INDICADOR — parte B. Ver `definiciones_a.py` por la regla
de escritura; acá va la segunda mitad del catálogo."""

DEF_B = {
# ── Vivienda y materiales ───────────────────────────────────────────────────
"pct_pared_ladrillo": "Viviendas con paredes de ladrillo, bloque de cemento u hormigón.",
"pct_pared_adobe": "Viviendas con paredes de adobe o tapial. No es precariedad por sí misma: bien mantenido es un material térmicamente bueno.",
"pct_pared_madera": "Viviendas con paredes de madera.",
"pct_pared_precaria": "Viviendas con paredes de caña, palma o tronco, materiales que no resisten una temporada de lluvias.",
"pct_revoque": "Viviendas cuyas paredes interiores están revocadas; el revoque es lo que sella la pared contra la humedad y los vectores.",
"pct_techo_calamina": "Viviendas con techo de calamina o plancha metálica.",
"pct_techo_teja": "Viviendas con techo de teja.",
"pct_techo_losa": "Viviendas con losa de hormigón armado, que además permite construir un piso encima.",
"pct_techo_paja": "Viviendas con techo de paja, palma, caña o barro.",
"pct_piso_tierra": "Viviendas donde se pisa tierra. Es el indicador de vivienda más asociado a enfermedades intestinales en la infancia.",
"pct_piso_cemento": "Viviendas con piso de cemento.",
"pct_piso_ceramica": "Viviendas con piso de cerámica, porcelanato o mosaico.",
"pct_monoambiente": "Viviendas de un solo cuarto, donde la misma pieza sirve para dormir, comer y estar.",
"pct_hacinamiento": "Viviendas donde duermen más de tres personas por dormitorio; es el umbral con el que se mide el hacinamiento crítico.",
"pers_x_dormitorio": "Cuántas personas duermen, en promedio, en cada dormitorio.",
"pct_choza": "Viviendas que son chozas o pahuichis.",
"pct_departamento": "Viviendas que son departamentos; su peso indica cuánto creció el municipio en altura y no en extensión.",
"pct_vivienda_desocupada": "Viviendas que existen pero nadie habita. Una proporción alta puede señalar loteamiento especulativo o migración.",
"viviendas": "Cuántas viviendas particulares ocupadas hay en el municipio.",
"pers_x_vivienda": "Cuántas personas viven, en promedio, en cada vivienda.",
"pers_x_habitacion": "Cuántas personas hay por cada cuarto, contando todos los ambientes salvo baño y cocina.",
"pct_hacinamiento_medio": "Viviendas con hacinamiento moderado, un escalón por debajo del crítico.",
"pct_pared_tabique": "Viviendas con paredes de tabique o quinche.",
"pct_piso_madera": "Viviendas con piso de madera, machihembre o parquet.",
"pct_piso_ladrillo": "Viviendas con piso de ladrillo.",
"pct_viv_colectiva": "Viviendas colectivas: cuarteles, conventos, internados, hoteles y residencias.",

# ── Tenencia ────────────────────────────────────────────────────────────────
"pct_viv_propia": "Hogares que son dueños de la casa donde viven, la estén terminando de pagar o no.",
"pct_viv_alquilada": "Hogares que pagan alquiler. Sube donde la población es más nueva: el que acaba de llegar todavía no compró.",
"pct_viv_anticretico": "Hogares en anticrético, la figura boliviana de préstamo con la vivienda en garantía.",
"pct_viv_prestada": "Hogares que ocupan una vivienda prestada por parientes o cedida a cambio de un servicio.",

# ── Educación ───────────────────────────────────────────────────────────────
"pct_analfabetismo": "Personas de quince años o más que no saben leer ni escribir.",
"pct_sin_educacion": "Personas adultas que no completaron ningún nivel educativo.",
"pct_edu_primaria": "Personas adultas cuyo máximo nivel alcanzado es la primaria.",
"pct_edu_secundaria": "Personas adultas cuyo máximo nivel alcanzado es la secundaria.",
"pct_edu_superior": "Personas adultas con estudios técnicos o universitarios. Es el indicador que más separa a unos municipios de otros.",
"prom_anios_estudio": "Cuántos años de escuela acumula, en promedio, una persona adulta.",
"pct_asistencia_escolar": "Niñas, niños y adolescentes en edad escolar que efectivamente están estudiando.",
"tasa_asistencia_4_5": "Niñas y niños de cuatro y cinco años que ya asisten a educación inicial.",
"tasa_asistencia_18_24": "Jóvenes que siguen estudiando después de la edad escolar obligatoria.",
"pct_secundaria_mas": "Personas adultas que terminaron al menos la secundaria.",
"pct_primaria_completa": "Personas adultas que completaron los seis años de primaria.",
"pct_rezago_escolar": "Adolescentes que van a un curso por debajo del que les corresponde por edad; mide el atraso acumulado, no el abandono.",
"pct_educacion_publica": "Estudiantes que asisten a un establecimiento público o de convenio, y no a uno privado.",
"brecha_alfabetismo": "Cuántos puntos separan a mujeres y hombres en saber leer y escribir. Un valor negativo indica desventaja femenina.",
"brecha_edu_superior": "Cuántos puntos separan a mujeres y hombres en llegar a la educación superior.",
"brecha_anios_estudio": "Cuántos años de escuela separan, en promedio, a las mujeres de los hombres.",
"brecha_edu_ninguno": "Cuántos puntos separan a mujeres y hombres entre quienes no completaron ningún nivel.",

# ── Salud ───────────────────────────────────────────────────────────────────
"pct_salud_publica": "Personas que, cuando se enferman, acuden a un puesto, centro u hospital público.",
"pct_caja_salud": "Personas que se atienden en una caja de salud, que es el sistema ligado al empleo formal.",
"pct_salud_privada": "Personas que se atienden en consultorios, clínicas u hospitales privados.",
"pct_salud_tradicional": "Personas que acuden a medicina tradicional ancestral.",
"pct_automedicacion": "Personas que van a la farmacia sin receta o se automedican; suele crecer donde el servicio está lejos.",
"pct_remedios_caseros": "Personas que resuelven con remedios caseros.",
"pct_seguro_salud": "Personas cubiertas por algún seguro: el SUS, una caja o un seguro privado.",
"pct_sus": "Personas afiliadas al Sistema Único de Salud, la cobertura pública universal.",
"pct_seguro_privado": "Personas con un seguro privado de salud.",
"pct_sin_seguro": "Personas sin ninguna afiliación de salud.",
"fecundidad": "Cuántos hijos ha tenido, en promedio, una mujer en edad fértil.",
"paridez_media": "Cuántos hijos ha tenido en toda su vida, en promedio, una mujer de doce años o más.",
"pct_madres_adolescentes": "Adolescentes de quince a diecinueve años que ya tuvieron al menos un hijo.",
"pct_hijos_fallecidos": "De todos los hijos nacidos vivos, qué proporción ya no vive. Es la huella de la mortalidad infantil pasada.",
"pct_parto_calificado": "Partos atendidos por personal de salud calificado, y no por partera o familiar.",
"edad_1er_hijo": "A qué edad tuvo, en promedio, su primer hijo.",
"brecha_sin_seguro": "Cuántos puntos separan a mujeres y hombres en quedar fuera de todo seguro de salud.",

# ── Empleo ──────────────────────────────────────────────────────────────────
"tasa_participacion": "Qué proporción de la población en edad de trabajar está trabajando o buscando trabajo.",
"tasa_ocupacion": "Qué proporción de la población en edad de trabajar tiene efectivamente una ocupación.",
"tasa_desocupacion": "De quienes están en el mercado laboral, cuántos buscan trabajo y no lo encuentran.",
"pct_asalariados": "Personas ocupadas que trabajan para un empleador a cambio de un sueldo.",
"pct_cuenta_propia": "Personas ocupadas que trabajan por su cuenta, sin patrón ni empleados.",
"pct_empleadores": "Personas ocupadas que emplean a otras.",
"pct_trab_familiar": "Personas que trabajan en el negocio o la parcela familiar sin recibir pago.",
"pct_sector_primario": "Personas ocupadas en agricultura, ganadería o minería: lo que se extrae de la tierra.",
"pct_sector_secundario": "Personas ocupadas en manufactura y construcción: lo que se transforma o se levanta.",
"pct_sector_servicios": "Personas ocupadas en servicios, que es donde trabaja la mayoría en una economía urbana.",
"pct_agricultura": "Personas ocupadas en agricultura.",
"pct_comercio": "Personas ocupadas en comercio al por mayor o menor, la rama más grande de la región.",
"pct_manufactura": "Personas ocupadas en la industria manufacturera.",
"pct_construccion": "Personas ocupadas en construcción, la rama que más responde al ciclo económico.",
"pct_transporte": "Personas ocupadas en transporte y almacenamiento.",
"pct_alojamiento": "Personas ocupadas en hoteles, restaurantes y servicios de comida.",
"pct_admin_publica": "Personas ocupadas en administración pública y defensa.",
"pct_ocu_profesionales": "Personas ocupadas en puestos directivos, profesionales o técnicos.",
"pct_ocu_no_calificado": "Personas ocupadas en trabajos que no exigen calificación previa.",
"brecha_participacion": "Cuántos puntos separan a hombres y mujeres en entrar al mercado de trabajo.",
"brecha_cuentapropia": "Cuántos puntos separan a mujeres y hombres en trabajar por cuenta propia.",
"pct_rama_ensenanza": "Personas ocupadas en enseñanza.",
"pct_rama_salud": "Personas ocupadas en salud y asistencia social.",
"brecha_cuenta_propia": "Cuántos puntos separan a mujeres y hombres en trabajar por cuenta propia.",

# ── Migración y territorio ──────────────────────────────────────────────────
"pct_nacido_otro_municipio": "Personas que viven acá pero nacieron en otro municipio. Es un stock sin fecha: no dice cuándo llegaron.",
"pct_nacido_extranjero": "Personas que viven acá y nacieron en otro país.",
"pct_migrante_reciente": "Personas que hace cinco años vivían en otro municipio. A diferencia del lugar de nacimiento, esto sí tiene fecha.",
"pct_residia_otro_mun": "Personas cuya residencia habitual declarada está en otro municipio.",
"saldo_migratorio": "Cuánta población ganó o perdió el municipio por mudanzas internas: los que llegaron menos los que se fueron.",
"pct_trabaja_fuera": "Personas ocupadas cuyo trabajo queda en otro municipio; no se mudaron, se desplazan todos los días.",
"pct_res5_extranjero": "Personas que hace cinco años vivían en otro país. Incluye tanto a extranjeros como a bolivianos que volvieron.",

# ── Flujos metropolitanos ───────────────────────────────────────────────────
"autocontencion_laboral": "Personas ocupadas que trabajan dentro de su propio municipio. Mide cuánto empleo genera un municipio para su propia gente.",
"dependencia_capital": "Personas ocupadas que van a trabajar a Santa Cruz de la Sierra.",
"poblacion_flotante": "Cuánta gente suma o resta el municipio de día por el movimiento del trabajo.",
"matriz_conmutacion": "De qué municipio a cuál se mueve la gente para trabajar, todos los pares a la vez.",
"matriz_migracion_nac": "Dónde nació y dónde vive hoy cada persona, todos los pares a la vez.",
"matriz_migracion_5a": "Dónde vivía hace cinco años y dónde vive hoy cada persona, todos los pares a la vez.",

# ── Pueblos, idiomas y ciudadanía ───────────────────────────────────────────
"pct_autoident_indigena": "Personas que se autoidentifican con alguna nación o pueblo indígena originario campesino o afroboliviano. Es autoidentificación declarada, no un rasgo asignado.",
"pct_quechua": "Personas que se autoidentifican como quechuas.",
"pct_aymara": "Personas que se autoidentifican como aymaras.",
"pct_guarani": "Personas que se autoidentifican como guaraníes.",
"pct_chiquitano": "Personas que se autoidentifican como chiquitanas o chiquitanos, el pueblo de mayor presencia histórica en la región.",
"pct_idioma_materno_originario": "Personas cuyo primer idioma fue una lengua originaria.",
"pct_idioma_materno_castellano": "Personas cuyo primer idioma fue el castellano.",
"pct_bilingue": "Personas que hablan dos o más idiomas.",
"pct_registro_civil": "Personas con su nacimiento inscrito en el registro civil boliviano.",
"pct_cedula_identidad": "Personas que tienen o tuvieron cédula de identidad boliviana. Sin cédula no hay trámite, banco ni voto.",
"pct_registro_menores5": "Niñas y niños menores de cinco años ya inscritos; es el indicador que anticipa la indocumentación futura.",

# ── Tecnología y equipamiento ───────────────────────────────────────────────
"pct_internet": "Hogares con internet, fijo o móvil.",
"pct_internet_fijo": "Hogares con conexión fija a internet. Es un gasto mensual voluntario, así que además revela capacidad de pago.",
"pct_internet_movil": "Hogares con internet por datos móviles, que es la vía de acceso donde no llega la red fija.",
"pct_computadora": "Hogares con computadora, laptop o tableta.",
"pct_celular": "Hogares con al menos un teléfono celular.",
"pct_tv_cable": "Hogares con televisión por cable o satelital.",
"pct_televisor": "Hogares con televisor.",
"pct_radio": "Hogares con radio o equipo de sonido.",
"pct_auto": "Hogares con vehículo automotor. Describe al hogar, no al viaje: el censo no pregunta en qué se mueve la gente.",
"pct_moto": "Hogares con motocicleta o cuadratrack.",
"pct_bicicleta": "Hogares con bicicleta.",
"pct_carreta": "Hogares con carreta o carretón.",
"pct_bote": "Hogares con deslizador, balsa, canoa o bote.",
"pct_refrigerador": "Hogares con refrigerador o congeladora.",
"pct_lavadora": "Hogares con lavadora de ropa.",
"pct_microondas": "Hogares con horno microondas.",
"pct_aire_acond": "Hogares con aire acondicionado, un gasto recurrente que en el llano oriental separa con claridad por nivel de vida.",

# ── Discapacidad ────────────────────────────────────────────────────────────
"pct_discapacidad": "Personas con alguna dificultad permanente para ver, oír, caminar o comunicarse.",
"pct_disc_ver": "Personas con dificultad severa para ver, incluso usando lentes.",
"pct_disc_oir": "Personas con dificultad severa para oír, incluso usando audífonos.",
"pct_disc_caminar": "Personas con dificultad severa para caminar, subir gradas o usar brazos y manos.",
"pct_disc_comunicar": "Personas con dificultad severa para comunicarse, aprender, concentrarse o recordar.",

# ── Pobreza (NBI) ───────────────────────────────────────────────────────────
"pct_nbi_pobre": "Población con al menos una necesidad básica insatisfecha, según la medición oficial del INE.",
"pct_nbi_no_pobre": "Población sin necesidades básicas insatisfechas.",
"pct_nbi_satisfechas": "Población cuyas necesidades básicas están cubiertas con holgura, el estrato más alto de la escala oficial.",
"pct_nbi_umbral": "Población justo en el límite: cubre lo básico, pero sin margen.",
"pct_nbi_moderada": "Población en pobreza moderada: le falta algo, pero no lo esencial de todo.",
"pct_nbi_indigente": "Población en indigencia, con carencias graves en varias dimensiones a la vez.",
"pct_nbi_marginal": "Población en marginalidad, el estrato de privación más extrema de la escala.",

# ── Componentes NBI ─────────────────────────────────────────────────────────
"pct_nbi_materiales": "Población cuya vivienda no alcanza el mínimo en paredes, techo o piso.",
"pct_nbi_espacios": "Población cuya vivienda no alcanza el mínimo de espacio: hacinamiento o falta de cuarto para cocinar.",
"pct_nbi_agua_sanea": "Población sin acceso adecuado a agua o a saneamiento.",
"pct_nbi_energia": "Población sin acceso adecuado a electricidad o a combustible para cocinar.",
"pct_nbi_educacion": "Población con rezago educativo según el mínimo que fija el método oficial.",
"pct_nbi_salud": "Población sin atención de salud adecuada según el método oficial.",

# ── Emigración internacional y mortalidad ───────────────────────────────────
"pct_con_emigrante": "Hogares que declararon que alguien que vivía con ellos hoy está en otro país.",
"emigrantes_x1000": "Cuántas personas emigradas al exterior hay por cada mil habitantes. Es memoria del hogar que se quedó: el que se fue completo no tiene quién lo declare.",
"pct_emi_argentina": "De quienes emigraron, qué proporción está en Argentina.",
"pct_emi_espana": "De quienes emigraron, qué proporción está en España.",
"pct_emi_brasil": "De quienes emigraron, qué proporción está en Brasil.",
"pct_emi_chile": "De quienes emigraron, qué proporción está en Chile, el destino principal de la región.",
"pct_emi_eeuu": "De quienes emigraron, qué proporción está en Estados Unidos.",
"edad_prom_emigracion": "A qué edad, en promedio, se fue del país quien emigró.",
"pct_hogar_fallecido": "Hogares donde murió alguien desde 2019.",
"tasa_mortalidad": "Cuántas muertes declaradas hay por cada mil habitantes. Es lo que el hogar recuerda, no un registro civil.",
"edad_prom_fallecimiento": "A qué edad, en promedio, murieron las personas declaradas.",

# ── Índices compuestos ──────────────────────────────────────────────────────
"idx_carencia": "Resume en un solo número cuántos servicios le faltan a la vivienda: agua, desagüe, electricidad, basura y combustible. Cuanto más alto, más carencia.",
"idx_calidad_vivienda": "Resume en un solo número la calidad material de la vivienda: paredes, techo, piso y hacinamiento.",
}
